// Simulates fetching data from an API
function mockFetch(query) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(
        [
          "Apple",
          "Banana",
          "Orange",
          "Grapes",
          "Strawberry",
          "Watermelon",
          "Pineapple",
          "Kiwi",
          "Peach",
          "Mango",
          "Blueberry",
          "Pear",
          "Cherry",
          "Plum",
          "Raspberry",
          "Apricot",
          "Pomegranate",
          "Cantaloupe",
          "Coconut",
          "Lemon",
          "Lime",
          "Blackberry",
          "Fig",
          "Guava",
          "Papaya",
          "Lychee",
          "Passionfruit",
          "Dragonfruit",
          "Avocado",
          "Cranberry",
          "Kumquat",
          "Tangerine",
          "Nectarine",
          "Persimmon",
          "Durian",
          "Starfruit",
          "Date",
          "Clementine",
          "Honeydew",
          "Carambola",
          "Melon",
          "Plantain",
          "Peach",
          "Gooseberry",
          "Tamarind",
          "Mulberry",
          "Currant",
          "Quince",
          "Elderberry",
          "Feijoa",
          "Rambutan",
          "Loquat",
          "Boysenberry",
          "Soursop",
          "Salak",
          "Sapodilla",
          "Surinam Cherry",
          "Ackee",
          "Bilberry",
          "Jabuticaba",
          "Jujube",
          "Langsat",
          "Pawpaw",
          "Persimmon",
          "Ugli Fruit",
          "Yuzu",
          "Cactus Pear",
          "Chayote",
          "Cupuacu",
          "Longan",
          "Miracle Fruit",
          "Pepino",
          "Tamarillo",
          "Yuzu",
          "Acai",
          "Barberry",
          "Pineberry",
          "Camu Camu",
          "Amla",
          "Cupuaçu",
          "Barbados Cherry",
          "Cloudberry",
          "Custard Apple",
          "Guanabana",
          "Huckleberry",
          "Juneberry",
          "Pepino",
          "Rowanberry",
          "Salmonberry",
          "Sea Buckthorn",
          "Feijoa",
          "Ginkgo",
          "Lingonberry",
          "African Cherry Orange",
          "Saskatoon Berry",
          "Surinam Cherry",
          "Tamarillo",
          "Tonka Bean",
          "Yumberries",
          "Raisin",
        ]
          .filter((item) =>
            item.toLocaleLowerCase().includes(query.toLocaleLowerCase())
          )
          .map((item) => ({ title: item }))
      );
    }, 1000); // simulate network delay
  });
}

export default mockFetch;
